#!/usr/bin/env python3
"""Generate repository indexes for agent-legible context."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = ROOT / "docs" / "generated"
MARKER = "<!-- Generated by scripts/refresh_generated_docs.py. Do not edit by hand. -->"


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    rendered = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        rendered.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(rendered)


def corpus_inventory() -> str:
    corpus_dir = ROOT / "data" / "past_markdown_files"
    raw_dir = ROOT / "data" / "past_raw_files"

    rows: list[list[object]] = []
    for path in sorted(corpus_dir.glob("*.md")):
        language = "Japanese" if "_J_" in path.name else "English" if "_E_" in path.name else "Unknown"
        rows.append([path.name, language, path.stat().st_size])

    raw_rows = [[path.name, path.stat().st_size] for path in sorted(raw_dir.glob("*.docx"))]

    return "\n\n".join(
        [
            MARKER,
            "",
            "# Corpus Inventory",
            "",
            f"- Markdown files: {len(rows)}",
            f"- Raw Word files: {len(raw_rows)}",
            "",
            "## Markdown Corpus",
            "",
            markdown_table(["file", "language", "bytes"], rows),
            "",
            "## Raw Sources",
            "",
            markdown_table(["file", "bytes"], raw_rows),
            "",
        ]
    )


def section_pair_summary() -> str:
    memory_path = ROOT / "data" / "knowledge" / "section_pairs.jsonl"
    records: list[dict[str, object]] = []
    if memory_path.exists():
        for line in memory_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                records.append(json.loads(line))

    by_year = Counter(str(record.get("year", "")) or "unknown" for record in records)
    by_label: Counter[str] = Counter()
    for record in records:
        for label in record.get("labels", []):
            by_label[str(label)] += 1

    return "\n\n".join(
        [
            MARKER,
            "",
            "# Section Pair Summary",
            "",
            f"- Source: `data/knowledge/section_pairs.jsonl`",
            f"- Total records: {len(records)}",
            "",
            "## Records By Year",
            "",
            markdown_table(["year", "records"], [[year, count] for year, count in sorted(by_year.items())]),
            "",
            "## Records By Label",
            "",
            markdown_table(["label", "records"], [[label, count] for label, count in sorted(by_label.items())]),
            "",
        ]
    )


def skill_index() -> str:
    rows: list[list[object]] = []
    scripts_by_skill: dict[str, list[str]] = defaultdict(list)

    for script_path in sorted((ROOT / "skills").glob("*/scripts/*")):
        if script_path.is_file():
            scripts_by_skill[script_path.parents[1].name].append(str(script_path.relative_to(ROOT)))

    for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
        text = skill_path.read_text(encoding="utf-8")
        name = ""
        description = ""
        for line in text.splitlines():
            if line.startswith("name: "):
                name = line.removeprefix("name: ").strip()
            if line.startswith("description: "):
                description = line.removeprefix("description: ").strip()
        skill_dir = skill_path.parent.name
        rows.append(
            [
                name or skill_dir,
                str(skill_path.relative_to(ROOT)),
                description,
                "<br>".join(scripts_by_skill.get(skill_dir, [])) or "-",
            ]
        )

    return "\n\n".join(
        [
            MARKER,
            "",
            "# Skill Index",
            "",
            markdown_table(["skill", "file", "description", "scripts"], rows),
            "",
        ]
    )


def generated_files() -> dict[Path, str]:
    return {
        GENERATED_DIR / "corpus-inventory.md": corpus_inventory(),
        GENERATED_DIR / "section-pair-summary.md": section_pair_summary(),
        GENERATED_DIR / "skill-index.md": skill_index(),
    }


def check_generated() -> int:
    failures: list[str] = []
    for path, expected in generated_files().items():
        if not path.exists():
            failures.append(f"{path.relative_to(ROOT)} is missing")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            failures.append(f"{path.relative_to(ROOT)} is stale")

    unexpected = [
        path
        for path in GENERATED_DIR.glob("*.md")
        if path not in generated_files()
    ]
    for path in unexpected:
        failures.append(f"{path.relative_to(ROOT)} is not produced by scripts/refresh_generated_docs.py")

    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    return 0


def write_generated() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in generated_files().items():
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Check generated docs without writing them.")
    args = parser.parse_args()

    if args.check:
        return check_generated()

    write_generated()
    print(f"Wrote generated docs to {GENERATED_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
